name: Evaluation

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    timeout-minutes: 3

    services:
        mongo:
          image: mongo:4.2.8
          ports:
            - 27017:27017
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check neptun.txt
        uses: akosdudas/ahk-action-neptuncheck@v1

      - name: Prepare .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.301"

      - name: Build sln
        run: dotnet build mongolab.sln

      - name: Evaluate
        uses: docker://akosdudas/sflab-ahk:mongo-2021
        env:
            DATABASE_CONNECTIONSTRING: "mongodb://mongo:27017/aaf"

      - name: Publish results
        uses: akosdudas/ahk-action-publish-result-pr@v1
        with:
          input-file: "result.txt"
          image-extension: ".png"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
