name: Evaluation

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    timeout-minutes: 3

    services:
        mongo:
          image: mongo:4.2.11
          ports:
            - 27017:27017
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check neptun.txt
        uses: akosdudas/ahk-action-neptuncheck@v1

      - name: Prepare .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build sln
        run: dotnet build mongolab.sln

      - name: Evaluate
        uses: docker://ghcr.io/bmeviauac01/sflab-ahk:mongo-2022
        env:
            DATABASE_CONNECTIONSTRING: "mongodb://mongo:27017/aaf"

      - name: Publish result
        uses: docker://ghcr.io/akosdudas/ahk-publish-results-pr:v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AHK_IMAGEEXT: ".png"
          AHK_APPTOKEN: "${{ secrets.AHK_APPTOKEN }}"
          AHK_APPSECRET: "${{ secrets.AHK_APPSECRET }}"
